### ISSUE TITLE
Adal8Angular issue when using hash location strategy

### ISSUE THREAD

**Issue by rcsprakash** [Macadoshis/adal-angular8#2]
Hi,
When we use hash location strategy. The page getting loaded twice after login process completed. 
The reload happened on handleCallBack method. It removes the hash and reload the page.
When compare the code with adal4 and adal8
adal4 accepts parameter handleWindowCallback(removeHash: boolean = true)
{
....
 // Remove hash from url
        if (removeHash) {
            if (window.location.hash) {
                if (window.history.replaceState) {
                    window.history.replaceState('', '/', window.location.pathname)
                } else {
                    window.location.hash = '';
                }
            }
        }
}
whether to remove hash or not, but in adal8 simply change the location
 if (window.location.hash) {
            window.location.href = window.location.href.replace(window.location.hash, '');
        }
if we make it as conditional based, will be more useful.

Thanks,
Suria.

**Comment by Macadoshis** [comment]
I've just published version 8.1.0 with :
- up-to-date merge from SalimDr/adal-angular5
- up-to-date merge from benbaran/adal-angular4

Please test it and let me now. I didn't test it, just compiled and published.

**Comment by rcsprakash** [comment]
HI,Thanks for the reply.I have tested the new version and receiving the following error.Can't resolve all parameters for Adal8Service: (?).

**Comment by Macadoshis** [comment]
Please test version 8.1.1.

**Comment by rcsprakash** [comment]
> Please test version 8.1.1.
Hi,
Thanks for the help. Its working fine now.

**Comment by Macadoshis** [comment]
Glad to hear about that. Thanks to you.
